mariadb:
    image: mariadb
    environment:
     - MYSQL_DATABASE=expense
     - MYSQL_USER=expense
     - MYSQL_PASSWORD=expense
     - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
     - ./database:/var/lib/mysql
    ports:
     - 127.0.0.1:3306:3306

