-- Category
SELECT * FROM CATEGORY;
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Arztkosten/Medikamente', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Auto', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Babyausstattung', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Drogerie', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Essen Büro Reh', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Essen Gehen', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Freizeit', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Geschenke', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Katzen', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Kleidung', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Lebenshaltung', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Lebensmittel', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('MVV', 'EXPENSE');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Gehalt Reh', 'INCOME');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Gehalt Hase', 'INCOME');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Kindergeld', 'INCOME');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Elterngeld Reh', 'INCOME');
--INSERT INTO CATEGORY (NAME, TYPE) VALUES ('Elterngeld Hase', 'INCOME');

-- Income
-- INSERT INTO INCOME (VALUE, NAME, VALID_FROM, VALID_THRU, TYPE, CATEGORY_ID) VALUES (1000, 'Gehalt 1', '2018-01-31', '2999-12-31', 'MONTHLY', 14);
-- INSERT INTO INCOME (VALUE, NAME, VALID_FROM, VALID_THRU, TYPE, CATEGORY_ID) VALUES (1000, 'Gehalt 2', '2018-01-31', '2999-12-31', 'MONTHLY', 15);

-- Expense
-- INSERT INTO EXPENSE (DATE, VALUE, CATEGORY_ID, TYPE) VALUES ('2018-01-15', 25, 2, 'NORMAL');
-- INSERT INTO EXPENSE (DATE, VALUE, CATEGORY_ID, TYPE) VALUES ('2018-01-17', 2.8, 4, 'NORMAL');